# Dependencies
markdown:         kramdown
highlighter:      rogue

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Kahlil.me
tagline:          'Tech blog'
description:      '"Computer Science is no more about computers than astronomy is about telescopes" -Dijkstra'
url:              http://kahlil.me
baseurl:          /

author:
  name:           'Kahlil Oppenheimer'
  url:            https://linkedin.com/in/kahliloppenheimer
  descriptions: 'programmer student author dota-er'

gems: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

# if you don't have any of social below, comment the line
facebook: kahliloppenheimer
twitter: uneditedjustice
# google: mygoogle
instagram: myinstagram
# pinterest: mypinterest
linkedin: kahliloppenheimer
#youtube: myyoutube
# spotify: https://open.spotify.com/user/1243784232
github: kahliloppenheimer
#medium: medium
email: kahliloppenheimer@gmail.com
