# Site settings
title: Kahlil Oppenheimer
tagline: Computer Science
email: kahliloppenheimer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Hi, I write computer programs that explore uncharted oceans...on Mars!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kahliloppenheimer.github.io" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Kahlil Oppenheimer"
author_thumbnail: "/assets/images/kahlil.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: kahliloppenheimer
    linkedIn: kahliloppenheimer
    twitter: uneditedjustice
    facebook: kahliloppenheimer
    gplus:
    # dribble: 
    pinterest: 

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  disqus_shortname: Kahlil

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
