# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Kahlil.me
tagline:          'Tech blog'
description:      '"Computer Science is no more about computers than astronomy is about telescopes" -Dijkstra'
url:              https://kahlil.me
baseurl:          /

author:
  name:           'Kahlil Oppenheimer'
  url:            https://linkedin.com/in/kahliloppenheimer

# Descriptions to shuffle through on about page
about-descriptions:
    - 'computer scientist'
    - 'lifelong vegetarian'
    - 'Brandeis University graduate'
    - 'machine learning enthusiast'
    - 'Square 2016 intern'
    - 'nodeJS experimenter'
    - 'dota gamer'
    - 'teaching assistant'
    - 'sailboat skipper'
    - 'KAYAK 2015 intern'
    - 'abstract algebraist'
    - 'wannabe journalist'
    - 'loop-pedal-er'
    - 'HP Vertica 2014 intern'
    - 'HubSpotter'
    - 'HbaseCon 2017 Speaker'
    - 'java microservice explorer'

plugins: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

excerpt_posts: true

excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

# if you don't have any of social below, comment the line
facebook: kahliloppenheimer
twitter: uneditedjustice
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: kahliloppenheimer
#youtube: myyoutube
# spotify: https://open.spotify.com/user/1243784232
github: kahliloppenheimer
#medium: medium
email: kahliloppenheimer@gmail.com
